services:
  db-ords-deploy:
    # define the mounted volumes for the DB/Apex apps 
    volumes:
      - ../modules/DSC/SQL:/usr/src/DSC/SQL
      - ../modules/AAM/CAS/application_code:/usr/src/CAS/application_code
      - ../modules/AAM/CAS/SQL:/usr/src/CAS/SQL
      - ../modules/AAM/SAM/SQL:/usr/src/SAM/SQL